---
title: why i am blogging
description: "why i am blogging and should you also blog? Why you (yes, you) should blog blogging with astro js as a machine learning engineer"
date: 2023-07-18
categories: [life,blogging,publish]
author: Kareem Elkhateb 
order: 1
---

## Table of contents

## Why I am blogging


1. I am blogging to establish a presence on the internet and hope to collaborate with people who are interested in what I write or think about (reducing the search space by reversing the process).
2. It serves as a resume and blueprint for my existence in this world.
3. My goal is to help others by providing valuable content that makes their lives easier and better.
4. Organizing my knowledge and recapping topics I've forgotten helps me experience "aha" moments! 💡
   1. It's a test of whether I truly understand something or not.
5. I don't like social media posts, Facebook, Twitter, or LinkedIn articles. I believe these platforms are not the best places for technical blogs, and their disadvantages outweigh the advantages.
6. I value the freedom of speech. Some topics or thoughts may be censored on social media, but I want to express my opinions without restrictions from others whose opinions I may not respect.
7. I want to discuss topics while I'm learning them because they're still fresh in my mind. This will help anyone in a similar position as me in the future.
8. When studying a topic and knowing that I can write about it on my blog, I find my mind more focused on details that would fit well in the blog. This makes the learning process more enjoyable, focused, and valuable.
9. I want my posts and knowledge to be more organized!
   1. Who will search for a post written six years ago on Facebook or see your first tweet?
   2. This problem is related to the feed of these social platforms.

## References

- https://medium.com/@racheltho/why-you-yes-you-should-blog-7d2544ac1045
